// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class Adress
    {
        public Adress()
        {
            Users = new HashSet<Users>();
        }

        public int AdressId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int PostalCode { get; set; }
        public string Cellphone { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}