// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class AnnouncementStatus
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CaptionPl { get; set; }
    }
}