// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class AttributeValueList
    {
        public AttributeValueList()
        {
            CategoryAttributes = new HashSet<CategoryAttributes>();
        }

        public int Id { get; set; }
        public int ListId { get; set; }
        public string Value { get; set; }
        public int FkCategoryAttrId { get; set; }
        public int FkProductAttrId { get; set; }

        public virtual ICollection<CategoryAttributes> CategoryAttributes { get; set; }
    }
}