// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class City
    {
        public City()
        {
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string City1 { get; set; }
        public string PostalCode { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}