// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class CompanyInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public string SmtpServer { get; set; }
        public int Port { get; set; }
        public string Pop3Server { get; set; }
        public string EmailPassword { get; set; }
        public string PostalCode { get; set; }
    }
}