// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class Conversations
    {
        public Conversations()
        {
            Comments = new HashSet<Comments>();
        }

        public int Id { get; set; }
        public string ProductId { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}