// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class Discounts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ValuePercent { get; set; }
        public double ValuePrice { get; set; }
        public DateTime EndDateTime { get; set; }

        public virtual DiscountsProducts DiscountsProducts { get; set; }
    }
}