// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class DiscountsProducts
    {
        public int Id { get; set; }
        public string IdProduct { get; set; }
        public int IdDiscount { get; set; }

        public virtual Discounts IdNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
    }
}