// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            OrderOpinion = new HashSet<OrderOpinion>();
        }

        public int OrderDetailId { get; set; }
        public int OneUserOrderId { get; set; }
        public string ProductId { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }

        public virtual OneUserOrder OneUserOrder { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderOpinion> OrderOpinion { get; set; }
    }
}