// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class Picture
    {
        public Picture()
        {
            OrderOpinion = new HashSet<OrderOpinion>();
        }

        public int PictureId { get; set; }
        public string Path { get; set; }
        public string ProdId { get; set; }

        public virtual Product Prod { get; set; }
        public virtual ICollection<OrderOpinion> OrderOpinion { get; set; }
    }
}