// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class ProductAttribute
    {
        public int ProductAttributeId { get; set; }
        public string Value { get; set; }
        public string ProductId { get; set; }
        public int CategoryAttributeId { get; set; }
        public bool IsRequired { get; set; }

        public virtual CategoryAttributes CategoryAttribute { get; set; }
        public virtual Product Product { get; set; }
    }
}