// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class Product
    {
        public Product()
        {
            Cart = new HashSet<Cart>();
            Comments = new HashSet<Comments>();
            Conversations = new HashSet<Conversations>();
            DiscountsProducts = new HashSet<DiscountsProducts>();
            OrderDetail = new HashSet<OrderDetail>();
            Picture = new HashSet<Picture>();
            ProductAttribute = new HashSet<ProductAttribute>();
        }

        public string ProductId { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ThumbPath { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public bool Removed { get; set; }
        public bool Hidden { get; set; }
        public int QuantityInStock { get; set; }
        public double? DiscountFromPrice { get; set; }
        public string AspNetUserId { get; set; }
        public DateTime CreationDate { get; set; }
        public int CityId { get; set; }
        public DateTime? DateTo { get; set; }

        public virtual Users AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Conversations> Conversations { get; set; }
        public virtual ICollection<DiscountsProducts> DiscountsProducts { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttribute { get; set; }
    }
}