// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class SupplyMethodType
    {
        public SupplyMethodType()
        {
            SupplyMethods = new HashSet<SupplyMethods>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SupplyMethods> SupplyMethods { get; set; }
    }
}