// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class SupplyMethods
    {
        public SupplyMethods()
        {
            UserSupplyMethod = new HashSet<UserSupplyMethod>();
        }

        public int Id { get; set; }
        public string Company { get; set; }
        public string SpecificDeliveryMethod { get; set; }
        public int SupplyMethodTypeId { get; set; }
        public string LogoPath { get; set; }

        public virtual SupplyMethodType SupplyMethodType { get; set; }
        public virtual ICollection<UserSupplyMethod> UserSupplyMethod { get; set; }
    }
}