// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class UserAccount
    {
        public int Id { get; set; }
        public DateTime OperationDate { get; set; }
        public decimal OperationAmount { get; set; }
        public string OrderSummaryId { get; set; }
        public int StatusId { get; set; }
        public string AccountNo { get; set; }
        public string UserId { get; set; }

        public virtual OrderSummary OrderSummary { get; set; }
        public virtual AccountOperationStatus Status { get; set; }
        public virtual Users User { get; set; }
    }
}