// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class UserProfileSettings
    {
        public UserProfileSettings()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public bool ShowNeedAgePics { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}