// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class UserSupplyMethod
    {
        public UserSupplyMethod()
        {
            OneUserOrder = new HashSet<OneUserOrder>();
        }

        public int Id { get; set; }
        public double PricePerUnit { get; set; }
        public double? PriceForManyUnits { get; set; }
        public int TimeInHours { get; set; }
        public int SupplyMethodId { get; set; }
        public string UserId { get; set; }
        public bool IsActive { get; set; }

        public virtual SupplyMethods SupplyMethod { get; set; }
        public virtual Users User { get; set; }
        public virtual ICollection<OneUserOrder> OneUserOrder { get; set; }
    }
}