// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace targeteo.pl.Model.Entities
{
    public partial class UserProfile
    {
        public UserProfile()
        {
            Users = new HashSet<Users>();
        }

        public int UserProfileId { get; set; }
        public string AcountNo { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}